### ISSUE TITLE
IDs for elements need to be added

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/react-navigation#1]
Test automation needs IDs (or name attributes) for elements. Those need to be unique on each page.

**Comment by kvolkovich-sc** [comment]
Added `data-test` attributes to most of interactive elements. If you want to add more, please create new issue.
https://github.com/OpusCapita/react-navigation/commit/d5d84e46a47c4e888b1bcd41784d28c6090e3301

**Comment by kvolkovich-sc** [comment]
As example with `data-test` attributes you can see at Facebook.com

![test-id](https://user-images.githubusercontent.com/24652543/31541963-f0ba7546-b018-11e7-8646-2cc65a7069e0.png)
