### ISSUE TITLE
React 16.x compatibility issue: probably old PropTypes definition still somewhere

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-navigation#10]
Library breaks app: 

```
TypeError: Cannot read property 'object' of undefined
```

![645654](https://user-images.githubusercontent.com/31243790/34096634-1de91426-e3e7-11e7-96bb-6e2389402c18.png)

Used here: https://github.com/OpusCapita/react-crudeditor/blob/master/src/demo/client/index.js

If I remove `@opuscapita/react-navigation` imports error disappears.

Package.json at the time of testing: 

```
"@opuscapita/npm-scripts": "2.0.1-beta.1",
"@opuscapita/react-navigation": "0.0.38",
"@opuscapita/react-reference-select": "2.0.1",
"@opuscapita/react-showroom-client": "1.3.0-beta.4",
"@opuscapita/react-showroom-server": "1.3.0",
"@opuscapita/styles": "1.0.0",
...
"react": "16.2.0",
"react-dom": "16.2.0",
"react-router": "4.2.0",
"react-router-dom": "4.1.2",
```

If I swap react to 15.6.2 error disappears.

**Comment by kvolkovich-sc** [comment]
Fixed
