### ISSUE TITLE
MenuIcon reserves height for hidden child elements on page load

### ISSUE THREAD

**Issue by jluukka** [OpusCapita/react-navigation#12]
MenuIcon-component reserves space for hidden child elements on page load. This appears to be because MenuIcon's "animationEnded" -state property is initially set to false. Showing and hiding the child elements again sets the height of child elements to 0.

**Comment by kvolkovich-sc** [comment]
The menu was improved.
See demo https://opuscapita.github.io/react-navigation/?currentComponentName=Menu
