### ISSUE TITLE
Search input field overlaps the logo in mobile screen

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/react-navigation#2]
![logo overlap1](https://user-images.githubusercontent.com/31068341/30796009-f0774800-a1d8-11e7-8d6a-3276026c55d0.png)

Search field could be shrunken to be as icon. Tapping an icon expands the input field shown as temporary, but that functionality is no needed to implement in this phase.

![logo overlap2](https://user-images.githubusercontent.com/31068341/30795864-51b1b99e-a1d8-11e7-8ede-d658867e28c9.png)

**Comment by kvolkovich-sc** [comment]
Hi @paiviheino !
I know about this problem. I'm going to continue working on the mobile version of the menu after the UX team approves any final version of mobile menu. Let me know when it's ready.

**Comment by kvolkovich-sc** [comment]
The menu layout for mobile screens was improved.
See demo https://opuscapita.github.io/react-navigation/?currentComponentName=Menu
