### ISSUE TITLE
Choosing active item from MenuDropdownGrid by id instead item index.

### ISSUE THREAD

**Issue by amogdalov-sc** [OpusCapita/react-navigation#20]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | ???h
Remaining Estimation | ???h

https://github.com/OpusCapita/minsk-core-externals/issues/109

**Comment by kvolkovich-sc** [comment]
Instead of using item id, "activeItem" property replaced by "active" property for each of items.

Configuration changes
===

- "activeItem" property replaced by "active" property for item itself.
  Relevant for "MenuDropdownGrid" and "NabigationBar" components.

**Comment by kvolkovich-sc** [comment]
Released in @opuscapita/react-navigation@3.0.0.
Please check.

**Comment by amogdalov-sc** [comment]
Implemented for SIM, INVT.
It's ok.
