### ISSUE TITLE
Application menu/picker in UI header behaviour change

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-navigation#28]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 4h
Remaining Estimation | 0h

### To Do:

* Hide icon if the corresponding app is not configured
* All icons arrange automatically (NO blank spaces, e.g. each line should not contain "wholes")

Origin issue https://github.com/OpusCapita/minsk-core-externals/issues/251

**Comment by asergeev-sc** [comment]
The last point is not needed here, please, rollback corresponding logic.

**Comment by dsanko-sc** [comment]
[Link to demo](https://opuscapita.github.io/react-navigation/branches/issue-28/?currentComponentName=Menu&maxContainerWidth=100%25)

**Comment by nstoliar-sc** [comment]
Tested. Icon for application in menu is displayed if application is not disabled and it has cofigured link. List of application has not blank spaces if some application is not cofigured. Please, merge with master branch.
