### ISSUE TITLE
Notifications popup is hidden from left in mobile screen

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/react-navigation#3]
It is not a “critical” bug, because not visible immediately in a view. But if someone tries to see what icons do, that popup gives a clear feeling of unfinished work.

![notification popup](https://user-images.githubusercontent.com/31068341/30796119-6241bf9c-a1d9-11e7-99c5-2a4979ea0464.png)

**Comment by kvolkovich-sc** [comment]
See my comment from [this issue](https://github.com/OpusCapita/react-navigation/issues/2)

**Comment by kvolkovich-sc** [comment]
The menu layout for mobile screens was improved.
See demo https://opuscapita.github.io/react-navigation/?currentComponentName=Menu
