### ISSUE TITLE
Use common styles instead of local

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-navigation#30]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 12h
Remaining Estimation | ???h

Description
---
We wont common markdown for navigation menu If we wont use common styles.

Solution
--
- remove local styles
- use markdown like in Grails navigation menu

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/492

**Comment by ddivin-sc** [comment]
Please, review my changes.

**Comment by ddivin-sc** [comment]
For QA: you can check it https://opuscapita.github.io/react-navigation/branches/issue-30/index.html?currentComponentName=Menu&maxContainerWidth=100%25

**Comment by asergeev-sc** [comment]
See my [comment](https://github.com/OpusCapita/react-navigation/pull/31#pullrequestreview-324079896) in PR

**Comment by ddivin-sc** [comment]
Done.

**Comment by nstoliar-sc** [comment]
Tested. UI of header is displayed correctly. Please, merge with master branch. 
Note: while merging please add correct link for user avatar (menuaccount, menuaccounticon).

**Comment by nstoliar-sc** [comment]
1. Please,  add correct link for user avatar (menuaccount, menuaccounticon).
![14](https://user-images.githubusercontent.com/25082017/69955553-f3122700-150e-11ea-9ab2-662fa92392c5.png)
2. Arrow for menu stoped displaying. 
![13](https://user-images.githubusercontent.com/25082017/69955610-1a68f400-150f-11ea-909f-4648678deb52.png)
3. User menu change color (became grey) after resizing. 
![14](https://user-images.githubusercontent.com/25082017/69955618-1f2da800-150f-11ea-9602-caf8570c8978.gif)

**Comment by ddivin-sc** [comment]
Fixed avatars and corner in menu item.

**Comment by nstoliar-sc** [comment]
Tested. UI of application header is displayed correctly. Please, merge with master branch.
