### ISSUE TITLE
Applications popup is hidden from left in mobile screen

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/react-navigation#4]
It is not a “critical” bug, because not visible immediately in a view. But if someone tries to see what icons do, that popup gives a clear feeling of unfinished work.

![applicaitons popup](https://user-images.githubusercontent.com/31068341/30796151-801708ba-a1d9-11e7-9723-c4ca215603dd.png)

**Comment by kvolkovich-sc** [comment]
See my comment from [this issue](https://github.com/OpusCapita/react-navigation/issues/2)

**Comment by kvolkovich-sc** [comment]
The menu layout for mobile screens was improved.
See demo https://opuscapita.github.io/react-navigation/?currentComponentName=Menu
