### ISSUE TITLE
There is no way of closing pop-out menus programmatically

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/react-navigation#5]
I have to be able to close pop-out menu layers from the code without having the user to click anywhere. This may apply to all the layers that can be triggered by menu icons.

![image](https://user-images.githubusercontent.com/25478114/31268450-96fdc39c-aa7c-11e7-92d0-1604282ac270.png)

**Comment by kvolkovich-sc** [comment]
https://github.com/OpusCapita/react-navigation/commit/493ff052baa9919511c48017a6f376617d58a020
