### ISSUE TITLE
Web element ID should be possible to be added for menu item components

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/react-navigation#6]
It should be possible to give the ID as parameter for menu item when using those in applications.

**Comment by kvolkovich-sc** [comment]
Done [here](https://github.com/OpusCapita/react-navigation/commit/7009c83ef426faf52c4c0ce02d8ff6f18996aa86)

Now you can pass any prop you need to navigationItems:

```
...
navigationItems={[
    { 
      children: 'Dashboard', 
      href: 'http://opuscapita.com', 
      target: '_blank', 
      id: 'nav-item-1' 
    },
...
```

If its OK, please close the issue.

**Comment by blomqsu1** [comment]
The ids need to be added also for menuIcon and MenuAccout components. 

![image](https://user-images.githubusercontent.com/31001652/32602810-3b113ed0-c550-11e7-914f-56266f029b2c.png)

**Comment by kvolkovich-sc** [comment]
Done.

**Comment by blomqsu1** [comment]
Thanks. Now it should be fine.
